name: GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify your Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Generate markdown files
        run: |
          python generate_chapter_markdowns.py

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_branch: gh-pages
