name: Auto Generate Index and Chapters

on:
  push:
    branches:
      - main  # Adjust based on your branch

jobs:
  build:
    name: Generate index and chapter pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip

      - name: Generate Index and Chapter Files
        run: |
          python ./.github/docgen.py

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add index.html Chapter*.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "[Auto] Generated index and chapter pages"; git push)
